#:schema node_modules/wrangler/config-schema.json
name = "worker-getting-started"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[ai]
binding = "AI"
